Feature 13269: cicd script (#41)
* refs #13269 github actions deployment automation
created cicd script that rebuilds and deploys to server a new version via docker compose and does strange stuff with logs

solved problems with permissions
deleted unnecessary file from root of proj

diff --git a/.github/workflows/front_deploy.yml b/.github/workflows/front_deploy.yml
--- a/.github/workflows/front_deploy.yml
+++ b/.github/workflows/front_deploy.yml
@@ -2,59 +2,107 @@ name: deploy-front
 
 on:
   push:
-    branches: 
-    - 13269-check
-    
+    branches:
+      - master
+
 jobs:
   connect_to_server:
     name: run pull
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04
 
     steps:
-    - name: Install ssh keys
-      run:
-        install -m 600 -D /dev/null ~/.ssh/front_rsa
-        echo "${{ secrets.FRONT_SSH_PRIVATE_KEY }}" > ~/.ssh/front_rsa
-        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
-    
-    - name: Connnect and pull
-      run: |
-        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
-          cd ${{ secrets.FRONT_WORK_DIR }} 
-          git checkout 13269-check
-          git pull
+    - name: Setup SSH directory
+      run: mkdir -p ~/.ssh
 
-          if [ ! -f env.front_vm]; then
-            git clone git@github.com:os-nsu/ostest-plan.git
+    - name: Install ssh keys
+      run: |
+        echo "${{ secrets.FRONT_SSH_PRIVATE_KEY }}" > ~/.ssh/front_rsa
+        chmod 600 ~/.ssh/front_rsa
+
+    - name: Add host to known_hosts
+      run: ssh-keyscan -H -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
+
+    - name: Add osplan SSH Key
+      run: |
+        echo "${{ secrets.OSPLAN_SSH_PRIVATE_KEY }}" > ~/.ssh/osplan_rsa
+        chmod 600 ~/.ssh/osplan_rsa
+
+    - name: Connect and pull
+      run: |
+        ssh -p ${{ secrets.SSH_PORT }} -i ~/.ssh/front_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
+        set -e
+
+        echo "----- Connected to server -----"
+
+          cd ${{ secrets.FRONT_WORK_DIR }}
+          echo "Now in project dir:"
+          pwd
+          ls -la
+
+          sudo chown -R ${{ secrets.SSH_USER }}:${{ secrets.SSH_USER }} *
+
+          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
+
+          eval "$(ssh-agent -s)"
+          ssh-add ~/.ssh/osplan_rsa
+
+          git reset --hard HEAD
+          git clean -fd
+          git fetch --all
+          git checkout master
+          git pull origin master
+
+          if [ ! -f env.front_vm ]; then
+            echo "env.front_vm not found. Cloning repository to fetch it..."
+
+            if ! git clone https://github.com/os-nsu/ostest-plan.git; then
+              echo "Failed to clone repository"
+              exit 1
+            fi
+
             mv ostest-plan/env.front_vm .
             rm -rf ostest-plan
+
+            echo "moved env file"
+          else
+            echo "env.front_vm already exists"
           fi
 
           exit
-        EOF
-      
-    - name: Cleanup
-      run: rm -rf ~/.ssh
-    
+        '
+
   build:
-      runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04
+    needs: connect_to_server
 
-      steps:
-        - name: Checkout repo
-          uses: actions/checkout@v3
+    steps:
+      - name: Setup SSH directory
+        run: mkdir -p ~/.ssh
 
-        - name: Deploy to our remote server
-          run: |
-            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
-              cd ${{ secrets.FRONT_WORK_DIR }}
-              git pull 
-              
-              docker-compose down
-              docker compose --env-file env.front_vm up --build
-            
-            EOF | tee deployment_log.txt
+      - name: Install ssh keys
+        run: |
+          echo "${{ secrets.FRONT_SSH_PRIVATE_KEY }}" > ~/.ssh/front_rsa
+          chmod 600 ~/.ssh/front_rsa
 
-        - name: See logs
-          uses: actions/upload-artifact@v4
-          with:
-            path: deployment_log.txt
+      - name: Add host to known_hosts
+        run: ssh-keyscan -H -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
+
+      - name: Checkout repo
+        uses: actions/checkout@v3
+
+      - name: Deploy to our remote server
+        run: |
+          set -e
+          ssh -p ${{ secrets.SSH_PORT }} -i ~/.ssh/front_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF | tee deployment_log.txt
+          cd ${{ secrets.FRONT_WORK_DIR }}
+          git pull
+          docker-compose down
+          docker compose --env-file env.front_vm up --build -d
+          sleep 10
+          docker logs $(docker ps -q --filter "ancestor=ostest-front-frontend")
+          EOF
+
+      - name: See logs
+        uses: actions/upload-artifact@v4
+        with:
+          path: deployment_log.txt
