added build job

diff --git a/.github/workflows/front_deploy.yml b/.github/workflows/front_deploy.yml
--- a/.github/workflows/front_deploy.yml
+++ b/.github/workflows/front_deploy.yml
@@ -58,12 +58,14 @@ jobs:
             echo "env.front_vm not found. Cloning repository to fetch it..."
             
             if ! git clone https://github.com/os-nsu/ostest-plan.git; then
-              echo "Failed to clone repository."
+              echo "Failed to clone repository"
               exit 1
             fi
 
             mv ostest-plan/env.front_vm .
             rm -rf ostest-plan
+
+            echo "moved env file"
           else
             echo "env.front_vm already exists"
           fi
@@ -73,47 +75,28 @@ jobs:
         
     - name: Cleanup
       run: rm -rf ~/.ssh
-    
-  # copy_env_file_to_front:
-  #   runs-on: ubuntu-latest
-  #   needs: connect_to_server
+     
+  build:
+    runs-on: ubuntu-latest
+    needs: connect_to_server
 
-  #   steps:
-  #   - name: Check and clone env file
-  #     run: |
-  #       ssh -p ${{ secrets.SSH_PORT }} -i ~/.ssh/front_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
-  #         cd ${{ secrets.FRONT_WORK_DIR }}
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v3
 
-  #         if [ ! -f env.front_vm ]; then
-  #           echo "env.front_vm not found. Cloning repository to fetch it..."
-  #           git clone git@github.com:os-nsu/ostest-plan.git
-  #           mv ostest-plan/env.front_vm .
-  #           rm -rf ostest-plan
-  #         else
-  #           echo "env.front_vm already exists"
-  #         fi
-  #       '
-
-  # build:
-  #   runs-on: ubuntu-latest
-  #   needs: connect_to_server
-
-  #   steps:
-  #     - name: Checkout repo
-  #       uses: actions/checkout@v3
-
-  #     - name: Deploy to our remote server
-  #       run: |
-  #         ssh -i ~/.ssh/front_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
-  #           cd ${{ secrets.FRONT_WORK_DIR }}
-  #           git pull 
+      - name: Deploy to our remote server
+        run: |
+          ssh -p ${{ secrets.SSH_PORT }} -i ~/.ssh/front_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
+          set -e
+            cd ${{ secrets.FRONT_WORK_DIR }}
+            git pull 
             
-  #           docker-compose down
-  #           docker compose --env-file env.front_vm up --build
+            docker-compose down
+            docker compose --env-file env.front_vm up --build
           
-  #         EOF | tee deployment_log.txt
+          EOF | tee deployment_log.txt
 
-  #     - name: See logs
-  #       uses: actions/upload-artifact@v4
-  #       with:
-  #         path: deployment_log.txt
+      - name: See logs
+        uses: actions/upload-artifact@v4
+        with:
+          path: deployment_log.txt
