added setting key in step + added e + if

diff --git a/.github/workflows/front_deploy.yml b/.github/workflows/front_deploy.yml
--- a/.github/workflows/front_deploy.yml
+++ b/.github/workflows/front_deploy.yml
@@ -36,7 +36,9 @@ jobs:
     - name: Connect and pull
       run: |
         ssh -p ${{ secrets.SSH_PORT }} -i ~/.ssh/front_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
-          echo "----- Connected to server -----"
+        set -e
+
+        echo "----- Connected to server -----"
           
           cd ${{ secrets.FRONT_WORK_DIR }} 
           echo "Now in project dir:"
@@ -45,13 +47,21 @@ jobs:
 
           ssh-keyscan -H github.com >> ~/.ssh/known_hosts
           
+          eval "$(ssh-agent -s)"
+          ssh-add ~/.ssh/osplan_rsa
+
           git fetch --all
           git checkout checkactions13269
           git pull origin checkactions13269
 
           if [ ! -f env.front_vm ]; then
             echo "env.front_vm not found. Cloning repository to fetch it..."
-            git clone git@github.com:os-nsu/ostest-plan.git
+            
+            if ! git clone git@github.com:os-nsu/ostest-plan.git; then
+              echo "Failed to clone repository."
+              exit 1
+            fi
+
             mv ostest-plan/env.front_vm .
             rm -rf ostest-plan
           else
